import { m as motion } from "@/lib/lazy-motion";
import SEO from "@/components/SEO";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

const Terms = () => {


  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="Terms of Service – Resonance YouTube Optimizer"
        description="The terms governing your use of Resonance YouTube Optimizer — accounts, billing, acceptable use and cancellation."
        path="/terms"
      />
      <SiteHeader />

      <main className="container mx-auto px-6 py-16 max-w-3xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-display font-bold text-4xl mb-2">Terms of Service</h1>
          <p className="text-muted-foreground text-sm mb-10">Last updated: March 29, 2026</p>

          <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Resonance YouTube Optimizer ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">2. Description of Service</h2>
              <p>Resonance YouTube Optimizer provides AI-powered tools for YouTube channel analysis, including but not limited to:</p>
              <ul className="list-disc ml-6 mt-2 space-y-1">
                <li>Channel health audits and scoring</li>
                <li>Thumbnail analysis and generation</li>
                <li>Content strategy recommendations</li>
                <li>Trend analysis and competitor insights</li>
                <li>Monetization opportunity identification</li>
                <li>Upload schedule optimization</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">3. User Responsibilities</h2>
              <ul className="list-disc ml-6 space-y-1">
                <li>You must provide accurate channel URLs for analysis.</li>
                <li>You may only analyze channels you own or have authorization to audit.</li>
                <li>You agree not to use the Service for any unlawful purpose or to violate any third-party rights.</li>
                <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">4. Intellectual Property</h2>
              <p>All content, branding, algorithms, and technology within the Service are the intellectual property of Resonance. You may not copy, modify, distribute, or reverse-engineer any part of the platform without express written permission.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">5. AI-Generated Content</h2>
              <p>Recommendations, thumbnails, and content ideas generated by our AI tools are provided as suggestions. You retain full ownership of content you create using our tools. We do not guarantee specific results from implementing our recommendations.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">6. Disclaimer of Warranties</h2>
              <p>The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee uninterrupted or error-free operation. YouTube growth metrics are projections based on AI analysis and are not guarantees of actual performance.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">7. Limitation of Liability</h2>
              <p>Resonance shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to lost revenue, channel performance changes, or data loss.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">8. Account Termination</h2>
              <p>We reserve the right to suspend or terminate your access to the Service at our discretion, particularly in cases of abuse, fraud, or violation of these terms. You may delete your account at any time by contacting our support team.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">9. Modifications to Terms</h2>
              <p>We may revise these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms. Material changes will be communicated via email or in-app notification.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">10. Governing Law</h2>
              <p>These Terms shall be governed by and construed in accordance with the laws of the Republic of South Africa. Any disputes shall be subject to the exclusive jurisdiction of the courts in Cape Town, South Africa.</p>
            </section>

            <section>
              <h2 className="font-display font-semibold text-lg text-foreground mb-3">11. Contact</h2>
              <p>For questions about these Terms, contact us at:</p>
              <ul className="list-none mt-2 space-y-1">
                <li>Email: <a href="mailto:support@resonance-podcast.com" className="text-primary hover:underline">support@resonance-podcast.com</a></li>
                <li>Phone: <a href="tel:+27832615492" className="text-primary hover:underline">+27 83 261 5492</a></li>
              </ul>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
};

export default Terms;
