"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";
type ImpactInput={id:string;job_id:string|null;session_id:string|null;source_type:string;source_user_id:string|null;content:string;created_at:string;impact_area:string;quality_score:number;acceptance_score:number;impact_score:number;points:number;lifecycle_state:string;scoring_version:string};
type ImpactArea={impact_area:string;input_count:number;points:number;avg_impact:number};
type ImpactStage={stage:string;input_count:number;points:number};
type Dashboard={scoring_version:string;policy:{quality_weight:number;acceptance_weight:number;max_score:number;points_unit:string;raw_activity_never_awards_points:boolean};summary:{input_count:number;avg_quality:number;avg_acceptance:number;avg_impact:number;total_points:number;certified_inputs:number;rejected_inputs:number};areas:ImpactArea[];stages:ImpactStage[];inputs:ImpactInput[];viewer_scope:"project"|"user";n0nymous_squad?:{status:string;criteria_version:string;thresholds:{minimum_points:number;minimum_certified_inputs:number;minimum_average_impact:number};self:{eligible_for_consideration:boolean;input_count:number;total_points:number;avg_quality:number;avg_impact:number;certified_inputs:number}}};
const stageLabel=(v:string)=>v.replaceAll("_"," ");
const scoreTone=(n:number)=>n>=80?"impactHigh":n>=60?"impactGood":n>=35?"impactMid":"impactLow";
function ScoreBar({value,label}:{value:number;label:string}){const safe=Math.max(0,Math.min(100,Number(value)||0));return <div className="impactBarWrap" aria-label={label+" "+Math.round(safe)+" out of 100"}><div className={"impactBar "+scoreTone(safe)} style={{width:safe+"%"}}/></div>}
export default function ImpactScoringWorkspace({projectId,currentUserId}:{projectId:string;currentUserId:string}){
 const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [selectedArea,setSelectedArea]=useState("ALL"); const [expandedId,setExpandedId]=useState<string|null>(null);
 const load=useCallback(async()=>{const supabase=getSupabase();if(!supabase)return;const {data,error:rpcError}=await supabase.rpc("get_project_impact_dashboard_v1",{target_project:projectId});if(rpcError){setError(rpcError.message);setLoading(false);return;}setDashboard((data||null) as Dashboard|null);setError("");setLoading(false)},[projectId,currentUserId]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer)},[load]);
 const inputs=useMemo(()=>!dashboard?[]:selectedArea==="ALL"?dashboard.inputs:dashboard.inputs.filter(item=>item.impact_area===selectedArea),[dashboard,selectedArea]);
 if(loading&&!dashboard)return <section className="panel"><p className="muted">Loading live impact scoring…</p></section>;
 if(error&&!dashboard)return <section className="panel"><p className="errorText">{error}</p><button className="secondaryButton compact" onClick={()=>void load()}>Retry</button></section>;
 if(!dashboard)return null; const summary=dashboard.summary;
 return <div className="impactWorkspace">
  <section className="heroPanel impactHero"><div className="heroCopy"><p className="eyebrow">PROJECT IMPACT · LIVE</p><h2>See what each input changes.</h2><p>Every DataNest AI input is scored against input quality and the stage it reaches in verification. Activity alone does not earn points; verified progression does.</p><div className="impactLegend"><span>0 · emerging</span><i/><span>100 · certified impact</span></div></div><div className="impactScoreOrb"><strong>{Math.round(summary.avg_impact)}</strong><span>AVG IMPACT</span></div></section>
  <section className="metricGrid impactMetrics"><article className="metricCard"><span>Inputs scored</span><strong>{summary.input_count}</strong><small>{dashboard.viewer_scope==="project"?"Project scope":"Your inputs"}</small></article><article className="metricCard"><span>Impact points</span><strong>{Math.round(summary.total_points)}</strong><small>Updated from live verification state</small></article><article className="metricCard"><span>Quality</span><strong>{Math.round(summary.avg_quality)}</strong><small>Input quality / 100</small></article><article className="metricCard"><span>Acceptance</span><strong>{Math.round(summary.avg_acceptance)}</strong><small>Verification stage / 100</small></article></section>
  <section className="panel impactSquadPanel"><div className="panelHead"><div><p className="eyebrow">N0NYMOUS SQUAD · CONSIDERATION</p><h3>Verified contribution pathway</h3></div><span className="countPill">{dashboard.n0nymous_squad?.self.eligible_for_consideration?"ELIGIBLE":"BUILDING"}</span></div><div className="impactSquadGrid"><div><strong>{Math.round(dashboard.n0nymous_squad?.self.total_points||0)}</strong><small>impact points</small></div><div><strong>{dashboard.n0nymous_squad?.self.certified_inputs||0}</strong><small>certified inputs</small></div><div><strong>{Math.round(dashboard.n0nymous_squad?.self.avg_impact||0)}</strong><small>average impact</small></div></div><p className="muted">This is a consideration signal, not automatic membership. v1 requires 100+ points, at least 1 certified input, and 60+ average impact. Identity is not used in the eligibility display.</p></section>\n  <section className="panel"><div className="panelHead"><div><p className="eyebrow">SCORING MODEL</p><h3>Quality × verification acceptance</h3></div><span className="countPill">{dashboard.scoring_version}</span></div><div className="impactFormula"><div><b>Quality</b><span>50%</span><ScoreBar value={summary.avg_quality} label="Average quality"/></div><div><b>Acceptance</b><span>50%</span><ScoreBar value={summary.avg_acceptance} label="Average acceptance"/></div><div className="impactFormulaResult"><b>Impact score</b><strong>{Math.round(summary.avg_impact)} / 100</strong></div></div><p className="muted">Quality measures clarity, structure and traceability. Acceptance increases only as linked knowledge reaches stronger verification stages. Raw AI usage, time and activity do not directly award points.</p></section>
  <section className="twoCol impactCols"><div className="panel"><div className="panelHead"><div><p className="eyebrow">PROJECT AREAS</p><h3>Where the work lands</h3></div></div><div className="impactAreaList"><button className={selectedArea==="ALL"?"impactArea active":"impactArea"} onClick={()=>setSelectedArea("ALL")}><span>All project areas</span><b>{Math.round(summary.total_points)}</b></button>{dashboard.areas.map(area=><button className={selectedArea===area.impact_area?"impactArea active":"impactArea"} key={area.impact_area} onClick={()=>setSelectedArea(area.impact_area)}><span><b>{area.impact_area}</b><small>{area.input_count} inputs · avg {Math.round(area.avg_impact)}</small></span><strong>{Math.round(area.points)} pts</strong></button>)}</div></div>
   <div className="panel"><div className="panelHead"><div><p className="eyebrow">VERIFICATION PIPELINE</p><h3>Stage acceptance</h3></div></div><div className="impactStageList">{dashboard.stages.map(stage=>{const v=stage.stage==="CERTIFIED"?100:stage.stage==="CERTIFICATION_REVIEW"?90:stage.stage==="STRESS_TESTED"?85:stage.stage==="VALIDATED"?75:stage.stage==="VERIFIED"?60:stage.stage==="AUDITED"?40:stage.stage==="NEEDS_EVIDENCE"?25:stage.stage==="REJECTED"?0:20;return <div className="impactStage" key={stage.stage}><div><b>{stageLabel(stage.stage)}</b><small>{stage.input_count} inputs · {Math.round(stage.points)} pts</small></div><ScoreBar value={v} label={stageLabel(stage.stage)}/></div>})}</div></div></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">INPUT-BY-INPUT TRACE</p><h3>Live contribution record</h3></div><span className="countPill">{inputs.length}</span></div>{inputs.length?<div className="impactInputList">{inputs.map(item=><article className="impactInput" key={item.id}><button className="impactInputHead" onClick={()=>setExpandedId(expandedId===item.id?null:item.id)}><span className={"impactScoreBadge "+scoreTone(item.impact_score)}>{Math.round(item.impact_score)}</span><span className="impactInputSummary"><b>{item.impact_area}</b><small>{stageLabel(item.lifecycle_state)} · {new Date(item.created_at).toLocaleString()}</small></span><span className="impactPoints">+{Math.round(item.points)} pts</span></button><div className="impactInputBars"><span>Quality <b>{Math.round(item.quality_score)}</b><ScoreBar value={item.quality_score} label="Input quality"/></span><span>Acceptance <b>{Math.round(item.acceptance_score)}</b><ScoreBar value={item.acceptance_score} label="Stage acceptance"/></span></div>{expandedId===item.id&&<div className="impactInputDetail"><p>{item.content}</p><small>{item.job_id?"JOB linked · "+item.job_id:"No Job linked"} · {item.source_type} · {item.scoring_version}</small></div>}</article>)}</div>:<div className="emptyState"><div>✦</div><h3>No inputs in this area</h3><p>Choose another project area to inspect live impact.</p></div>}</section>
  <p className="impactPrivacyNote">The dashboard is scoped to the authenticated user unless they have project Owner/Admin access. N0nymous Squad eligibility can be generated from verified contribution evidence without exposing raw identity.</p>
 </div>;
}