-- Provider-neutral PayFast ITN settlement state for the sovereign backend.
-- The Hub validates PayFast signature/server response/SKU amount before calling the keyed procedure.
-- Raw PayFast payloads, merchant credentials, passphrases, card data and payment tokens are never persisted here.

CREATE TABLE IF NOT EXISTS public.payfast_itn_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  signature_valid BOOLEAN NOT NULL,
  server_validated BOOLEAN NOT NULL,
  outcome TEXT NOT NULL,
  http_status INTEGER NOT NULL CHECK (http_status BETWEEN 100 AND 599),
  sku TEXT,
  user_id UUID,
  amount_cents INTEGER,
  payment_status TEXT,
  pf_payment_id TEXT,
  source_ip TEXT,
  payload_hash TEXT NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
  error_message TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS payfast_itn_logs_received_idx
  ON public.payfast_itn_logs(received_at DESC);
CREATE INDEX IF NOT EXISTS payfast_itn_logs_pf_idx
  ON public.payfast_itn_logs(pf_payment_id) WHERE pf_payment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.webhook_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider TEXT NOT NULL,
  event_id TEXT NOT NULL,
  payload_hash TEXT NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
  http_status INTEGER,
  outcome TEXT,
  response_body TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT webhook_events_provider_event_unique UNIQUE(provider,event_id)
);
CREATE INDEX IF NOT EXISTS webhook_events_provider_seen_idx
  ON public.webhook_events(provider,first_seen_at DESC);

CREATE TABLE IF NOT EXISTS public.plan_changes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  from_sub_id UUID REFERENCES public.subscriptions(id) ON DELETE SET NULL,
  to_sub_id UUID REFERENCES public.subscriptions(id) ON DELETE SET NULL,
  from_app TEXT,
  from_tier TEXT,
  to_app TEXT NOT NULL,
  to_tier TEXT NOT NULL,
  change_type TEXT NOT NULL CHECK (
    change_type IN ('upgrade','downgrade','sidegrade','initial','supersede','cancel','refund')
  ),
  reason TEXT,
  pf_payment_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS plan_changes_user_created_idx
  ON public.plan_changes(user_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.subscription_email_sends (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pf_payment_id TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL,
  recipient_email TEXT NOT NULL,
  sku TEXT NOT NULL,
  app TEXT NOT NULL,
  tier TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  skipped_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS subscription_email_sends_user_idx
  ON public.subscription_email_sends(user_id);
CREATE INDEX IF NOT EXISTS subscription_email_sends_recipient_idx
  ON public.subscription_email_sends(recipient_email);

CREATE TABLE IF NOT EXISTS public.email_suppression_list (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.payfast_itn_logs IS
  'Sanitized PayFast ITN outcome audit. Raw provider payloads and secrets are intentionally excluded.';
COMMENT ON TABLE public.webhook_events IS
  'Provider event idempotency ledger for validated webhooks.';
COMMENT ON TABLE public.plan_changes IS
  'Subscription transition audit generated by keyed backend settlement procedures.';
COMMENT ON TABLE public.subscription_email_sends IS
  'Idempotent subscription-confirmation queue metadata; no email provider secret is stored.';
