import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Play, Music, Clock, Sparkles } from "lucide-react";

import midnight01 from "@/assets/storyboards/midnight-01.jpg";
import midnight02 from "@/assets/storyboards/midnight-02.jpg";
import midnight03 from "@/assets/storyboards/midnight-03.jpg";
import sunfire01 from "@/assets/storyboards/sunfire-01.jpg";
import sunfire02 from "@/assets/storyboards/sunfire-02.jpg";
import sunfire03 from "@/assets/storyboards/sunfire-03.jpg";
import coldroom01 from "@/assets/storyboards/coldroom-01.jpg";
import coldroom02 from "@/assets/storyboards/coldroom-02.jpg";
import coldroom03 from "@/assets/storyboards/coldroom-03.jpg";

type Frame = {
  img: string;
  scene: string;      // e.g. "S01 · Intro"
  ts: string;         // e.g. "00:00–00:18"
  lyric: string;      // caption line
  note: string;       // director note
};

type Board = {
  id: string;
  track: string;
  genre: string;
  bpm: number;
  keySig: string;
  length: string;
  hue: number;
  frames: Frame[];
};

const BOARDS: Board[] = [
  {
    id: "midnight",
    track: "Midnight Skyline",
    genre: "Synthwave R&B",
    bpm: 96,
    keySig: "F# min",
    length: "3:14",
    hue: 325,
    frames: [
      { img: midnight01, scene: "S01 · Intro",   ts: "00:00–00:18", lyric: "City lights are calling out my name",  note: "Wide skyline, slow push-in" },
      { img: midnight02, scene: "S02 · Verse",   ts: "00:18–00:46", lyric: "Neon rivers flow beneath the rain",     note: "Rain-soaked alley, silhouette walk" },
      { img: midnight03, scene: "S03 · Chorus",  ts: "00:46–01:12", lyric: "Tonight the skyline learns our name",   note: "Rooftop, rim-lit arms-wide hero shot" },
    ],
  },
  {
    id: "sunfire",
    track: "Sunfire",
    genre: "Afrobeats",
    bpm: 108,
    keySig: "A maj",
    length: "2:52",
    hue: 30,
    frames: [
      { img: sunfire01, scene: "S01 · Intro",   ts: "00:00–00:12", lyric: "Sun on the pavement, feet in the sand",   note: "Golden-hour street, dust and haze" },
      { img: sunfire02, scene: "S02 · Verse",   ts: "00:12–00:40", lyric: "Bodies moving like the ocean sway",       note: "Wide dance shot, motion blur limbs" },
      { img: sunfire03, scene: "S03 · Bridge",  ts: "00:40–01:04", lyric: "Golden hour on your golden skin",         note: "Portrait close-up, warm rim light" },
    ],
  },
  {
    id: "coldroom",
    track: "Cold Room",
    genre: "Dark Trap",
    bpm: 140,
    keySig: "C# min",
    length: "2:33",
    hue: 200,
    frames: [
      { img: coldroom01, scene: "S01 · Intro",   ts: "00:00–00:14", lyric: "Empty walls, they don't say much",       note: "Overhead pendant, empty room" },
      { img: coldroom02, scene: "S02 · Verse",   ts: "00:14–00:42", lyric: "Hood up, head down, keep it moving",     note: "Low-angle hoodie under fluorescent" },
      { img: coldroom03, scene: "S03 · Chorus",  ts: "00:42–01:08", lyric: "Cold room, cold heart, still I glow",    note: "Close-up hands + chain, cold grade" },
    ],
  },
];

export function StoryboardGallery() {
  const [active, setActive] = useState<string>(BOARDS[0].id);
  const board = BOARDS.find((b) => b.id === active) ?? BOARDS[0];

  return (
    <section className="border-t border-white/5 bg-gradient-to-b from-background via-secondary/10 to-background">
      <div className="container py-16">
        {/* Header */}
        <div className="mb-8 flex flex-col items-start justify-between gap-4 md:flex-row md:items-end">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-card/60 px-3 py-1 font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-muted-foreground backdrop-blur-xl">
              <Sparkles className="h-3 w-3 text-accent" /> Real output · from three real tracks
            </div>
            <h2 className="mt-4 text-2xl font-bold sm:text-3xl">
              Storyboards Sync Vision has made
            </h2>
            <p className="mt-2 max-w-xl text-sm text-muted-foreground">
              Every frame here was generated by the same pipeline you'll use on your track — locked to
              a lyric window, a downbeat, and a consistent character.
            </p>
          </div>

          {/* Track tabs */}
          <div className="flex flex-wrap gap-2">
            {BOARDS.map((b) => {
              const isActive = b.id === active;
              return (
                <button
                  key={b.id}
                  onClick={() => setActive(b.id)}
                  className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold transition-colors ${
                    isActive
                      ? "border-white/25 bg-white/[0.06] text-foreground"
                      : "border-white/10 bg-transparent text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <span
                    className="h-2 w-2 rounded-full"
                    style={{ background: `hsl(${b.hue} 90% 65%)`, boxShadow: `0 0 8px hsl(${b.hue} 90% 65% / 0.8)` }}
                  />
                  {b.track}
                </button>
              );
            })}
          </div>
        </div>

        {/* Board card */}
        <AnimatePresence mode="wait">
          <motion.div
            key={board.id}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.35 }}
            className="overflow-hidden rounded-3xl border border-white/10 bg-card/40 backdrop-blur-xl"
          >
            {/* Track meta bar */}
            <div className="flex flex-wrap items-center gap-x-6 gap-y-2 border-b border-white/10 bg-background/40 px-5 py-3 text-xs">
              <div className="flex items-center gap-2 font-semibold">
                <span
                  className="flex h-6 w-6 items-center justify-center rounded-md"
                  style={{ background: `hsl(${board.hue} 90% 60% / 0.15)`, color: `hsl(${board.hue} 90% 75%)` }}
                >
                  <Music className="h-3 w-3" />
                </span>
                <span className="text-foreground">{board.track}</span>
                <span className="text-muted-foreground">· {board.genre}</span>
              </div>
              <div className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
                <span className="gradient-text font-bold">{board.bpm}</span> BPM
              </div>
              <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
                Key <span className="text-foreground">{board.keySig}</span>
              </div>
              <div className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
                <Clock className="h-3 w-3" /> {board.length}
              </div>
              <div className="ml-auto flex items-center gap-1.5 rounded-full border border-white/10 bg-background/60 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.22em] text-primary">
                <Play className="h-3 w-3" /> Character locked
              </div>
            </div>

            {/* Frames grid */}
            <div className="grid gap-4 p-5 md:grid-cols-3">
              {board.frames.map((f, i) => (
                <motion.figure
                  key={f.scene}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="group overflow-hidden rounded-2xl border border-white/10 bg-background/40"
                >
                  <div className="relative aspect-video overflow-hidden">
                    <img
                      src={f.img}
                      alt={`${board.track} — ${f.scene}`}
                      width={1024}
                      height={576}
                      loading="lazy"
                      className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
                    />
                    <div className="absolute left-2 top-2 rounded-md border border-white/15 bg-black/50 px-2 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-[0.22em] text-white/90 backdrop-blur">
                      {f.scene}
                    </div>
                    <div className="absolute right-2 top-2 rounded-md border border-white/15 bg-black/50 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.22em] text-white/80 backdrop-blur">
                      {f.ts}
                    </div>
                    {/* Karaoke-style caption */}
                    <div className="absolute inset-x-2 bottom-2 rounded-md bg-gradient-to-t from-black/85 via-black/50 to-transparent p-2.5">
                      <div className="text-[13px] font-semibold leading-snug text-white drop-shadow">
                        {f.lyric}
                      </div>
                    </div>
                  </div>
                  <figcaption className="px-3 py-2.5">
                    <div className="font-mono text-[9px] font-semibold uppercase tracking-[0.22em] text-muted-foreground">
                      Director note
                    </div>
                    <div className="mt-0.5 text-[12px] text-foreground/90">{f.note}</div>
                  </figcaption>
                </motion.figure>
              ))}
            </div>
          </motion.div>
        </AnimatePresence>

        <p className="mt-4 text-center text-[11px] text-muted-foreground">
          Rendered scenes shown — every frame was produced by Sync Vision from an uploaded track.
        </p>
      </div>
    </section>
  );
}
